[package]
name = "rxenstored"
version = "0.1.0"
authors = ["Doug Goldstein <cardoe@cardoe.com>"]

[dependencies]
clap = "2.18.0"
libxenstore = { path = "../libxenstore" }
log = "^0.3"
nix = "0.6.0"
stderrlog = "^0.2.1"
tokio-uds-proto = "^0.1"
